apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
        - name: flask-hello
          image: igpino97/flask-hello:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000